### ISSUE TITLE
Incoherent results between documentation and date-fns console repl

### ISSUE THREAD

**Issue by manueledones** [date-fns/date-fns#1533] opened 2019-11-05 07:30 UTC
It looks like the dateFns object in the date-fns documentation pages is outdated.

For example:

![image](https://user-images.githubusercontent.com/22741818/68187244-79862800-ffa6-11e9-81f4-77b0cd9f6b28.png)

But the docs [here ](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md) says to use yyyy instead of YYYY, I suppose the docs embed a version 1...

**Comment by 102** [comment] 2019-11-05 07:39
#1502

**Comment by kossnocorp** [comment] 2019-11-05 07:44
Duplicate of: https://github.com/date-fns/date-fns.org/issues/124

**Closed by kossnocorp** 2019-11-05 07:44 UTC
Labels: ↩️ Duplicate
