### ISSUE TITLE
Transaction history is giving previous day instead of current day when a transaction is processed

### ISSUE THREAD

**Issue by ldco2016** [date-fns/date-fns#1622] opened 2020-01-30 14:32 UTC
Describe the bug
When a user purchases a ticket for an event on 01/29, the transaction history shows the date of purchase as being 01/28.

Expected behavior
I expect that the transaction date should be whatever day the ticket was purchased.

Additional context

```
import React from 'react';
import {View, Text, StyleSheet, ScrollView} from 'react-native';
import EmptyTransactions from './EmptyTransactions';
import {Divider} from 'common-components';
import {v2Colors, v2Fonts} from 'theme';
import format from 'date-fns/format';
import PropTypes from 'prop-types';

const propTypes = {
  transactions: PropTypes.array,
};

const TransactionsTable = ({transactions = []}) => (
  <View style={styles.container}>
    <View style={styles.tableHeader}>
      <View style={styles.headerCol}>
        <Text style={styles.text}>{'DATE'}</Text>
      </View>
      <View style={styles.headerCol}>
        <Text style={styles.text}>{'PRODUCT'}</Text>
      </View>
      <View style={styles.headerCol}>
        <Text style={styles.text}>{'METHOD'}</Text>
      </View>
      <View style={styles.headerCol}>
        <Text style={styles.text}>{'$'}</Text>
      </View>
    </View>
    {!transactions.length && <EmptyTransactions />}
    {Boolean(transactions.length) && (
      <ScrollView showsVerticalScrollIndicator={false}>
        {transactions.map(t => (
          <View key={t.Key}>
            <View style={styles.tableRow}>
              <View style={styles.headerCol}>
                <Text style={styles.text}>
                  {format(t.DateTime, 'MM-DD-YYYY')}
                </Text>
```

The version number of `date-fns` is `1.29.0`.

**Comment by miketeix** [comment] 2020-02-05 14:32
I've had similar issues with the format function. It seems to work fine when the page is viewed in Europe but it is almost always the day before when viewed from North America, hopefully that helps!

**Comment by papiro** [comment] 2020-04-29 11:55
Experiencing this same issue. Have a Jest test basically asserting `format(12345, 'MM/dd/yyyy')` to be "01/01/1970" which runs as expected on my machine and in the CI/CD pipeline but on one developer's machine who is in the same timezone (in North America), the test fails and the date produced is "12/31/1969". Is there some sort of option I'm missing?

**Comment by dcousens** [comment] 2020-04-29 12:50
@ldco2016 @miketeix  pleases provide an example that can be reproduced. 

@papiro, your example, when run with `TZ=US/Pacific node`
```js
const df = require('date-fns')
console.log(df.format(0, 'yyyy-MM-dd HH:mm'))
> 1969-12-31 16:00
```

Is expected as the time provided is **UTC** milliseconds.

**Comment by papiro** [comment] 2020-04-29 14:12
@dcousens, thank you for your quick reply. My timezone is America/New_York. I am not getting `12/31/1969` for my example when I was getting `01/01/1970` when testing (same timezone) at that particular time yesterday. I imagine it will change again, even without changing my timezone. It seems like a bug to me because the localized display of a time (in ms) in the past should not depend on the time of day at current. Am I missing something?

**Comment by dkozickis** [comment] 2020-05-01 08:53
@papiro what is your dev environment? Did you change it lately? Did you update node version/OS version/Browser version?

**Comment by papiro** [comment] 2020-05-01 19:17
@dkozickis @dcousens I apologize. Am I the only one who thinks date-times are complex? I didn't realize that the container I was running tests in has a timezone of UTC:
```
root@ad1d2e1a7841:/workspaces/sa# date
Fri May  1 19:15:16 UTC 2020
```
I think I was then doing some sanity checks in my workspace, outside of the container... Didn't notice they were different:
```
/home/pir3103/sa: date
Fri May  1 13:16:48 MDT 2020
```

**Comment by dcousens** [comment] 2020-05-02 02:24
> Am I the only one who thinks date-times are complex?

This library wouldn't exist if you did :stuck_out_tongue:

**Comment by dkozickis** [comment] 2020-05-02 18:05
I wish everyone spoke in Zulu time always 🤷🏻‍♂️

I will close this for now, please reopen if you’re able to provide a reproducer.

**Closed by dkozickis** 2020-05-02 18:05 UTC
