### ISSUE TITLE
make date-fns v2 available on the docs website

### ISSUE THREAD

**Issue by gwmccull** [date-fns/date-fns#1515] opened 2019-10-30 17:53 UTC
It looks like the documentation website still has version 1 of the date-fns library attached to the window object. I'm basing this on the fact that there's no `window.dateFns.formatDistance` function but there still is a `window.dateFns.distanceInWords` function

**Comment by dkozickis** [comment] 2019-11-02 06:06
Duplicate of https://github.com/date-fns/date-fns.org/issues/124 

Hopefully we'll get around to updating this at some point =/

**Closed by dkozickis** 2019-11-02 06:06 UTC
