### ISSUE TITLE
Website's init function blocked by CORS

### ISSUE THREAD

**Issue by Matias-A** [date-fns/date-fns#3334] opened 2023-01-31 12:54 UTC
Running `init()` to test date-fns functions from the website seems to be failing with a CORS issue
<img width="667" alt="Screenshot 2023-01-31 at 14 52 47" src="https://user-images.githubusercontent.com/8319613/215765327-5d11d157-5f0a-4bc2-ae04-5e7d8b72bd57.png">

**Comment by fturmel** [comment] 2023-01-31 19:52
Can't reproduce it on my end. Maybe it was a temporary unpkg issue that was corrected?

<img width="414" alt="Screenshot 2023-01-31 at 2 47 56 PM" src="https://user-images.githubusercontent.com/4009209/215866737-8de32d75-51d8-4cd4-b77b-fe0ba1859509.png">


<img width="454" alt="Screenshot 2023-01-31 at 2 52 00 PM" src="https://user-images.githubusercontent.com/4009209/215867593-cc6f13f5-96d2-45d6-a423-30a94e3bc5df.png">

**Comment by fturmel** [comment] 2023-01-31 19:58
Going to close this per my previous comment, but if it persists we can reopen.

**Closed by fturmel** 2023-01-31 19:58 UTC

**Comment by FezVrasta** [comment] 2024-11-15 11:48
![CleanShot 2024-11-15 at 12  48 18@2x](https://github.com/user-attachments/assets/65e26324-cfe5-4a94-ba71-9708653f3839)

This has been happening consistently for me for the past months.
