### ISSUE TITLE
Error subpath node 20 date-fns(3.0.0) and date-fns-tz(2.0.0)

### ISSUE THREAD

**Issue by agasparo** [date-fns/date-fns#3613] opened 2023-12-19 09:35 UTC
On node 20 if you install `date-fns 3.0.0 (latest)` and `date-fns-tz 2.0.0 (latest)`, with `type : commonJs` in package.json you will have this error

`Package subpath './format/index.js' is not defined by "exports" in /app/node_modules/.pnpm/date-fns-tz@2.0.0_date-fns@3.0.0/node_modules/date-fns/package.json`

Screenshot : 

![Screenshot 2023-12-19 at 10 34 36](https://github.com/date-fns/date-fns/assets/47241652/1c7ea6e4-8c48-4ef1-90e5-3ca591abe0cf)

**Comment by alihuber** [comment] 2023-12-19 11:20
possible duplicate of https://github.com/date-fns/date-fns/issues/3612 ?

**Comment by kossnocorp** [comment] 2023-12-21 00:53
`date-fns-tz` is currently incompatible with date-fns v3, you can follow the progress here: https://github.com/marnusw/date-fns-tz/issues/260

**Closed by kossnocorp** 2023-12-21 00:53 UTC
