### ISSUE TITLE
format('2018-13-01', 'YYYY-MM-DD') sets date to 2019-01-01

### ISSUE THREAD

**Issue by MikaelEdebro** [date-fns/date-fns#719] opened 2018-03-25 20:19 UTC
I encountered something strange today when testing around. Not sure if it's by design or a bug?

When using incorrect month (13), it figures that it's 12+1, and sets date to next year.
Shouldn't it return "Invalid date" or something like that?

https://jsfiddle.net/at9vtofg/8/

**Comment by dasDaniel** [comment] 2018-04-04 21:18
this "feature" can be handy, but should have an option parameter set to allow this kind of rollover, but not by default.

I tried using isValid() function, but that expects a date to be passed, which seems to defeat the purpose, because you can tell from `new Date('2018-13-01')` that it's wrong.

**Comment by bmcminn** [comment] 2018-04-25 16:03
@dasDaniel, That depends on the locale being parsed. ISO 8601 Australian dates specify `YYYY-DD-MM`, so that would be a valid date string as January 13, 2018. This is true for many other locales as well.

**Comment by leshakoss** [comment] 2018-04-25 16:09
@bmcminn what? no, ISO 8601 is locale independent

**Comment by leshakoss** [comment] 2018-04-25 16:09
The issue is the duplicate of #347

**Comment by bmcminn** [comment] 2018-04-25 16:44
@leshakoss Yes, the spec itself is, but unless locale is factored into date parsing, you get wierd artifacts in the way of wrong dates. I've seen this issue in production systems where the client apps respected client date locales, but the backend relied on their system locale definitions when processing date transformations.

In practice, it's a systems level business logic concern, but at the library level, determining if a date is valid should be informed by the locale being parsed.

**Comment by dasDaniel** [comment] 2018-04-25 17:08
the I in ISO is for International, the definition of ISO 8601 doesn't change based on locale.
the javascript `new Date` accepts a dateString defined as 

> String value representing a date. The string should be in a format recognized by the Date.parse() method (IETF-compliant RFC 2822 timestamps and also a version of ISO8601). 

so unless the  format is specifically defined, as in `format('2018-13-01', 'YYYY-DD-MM') `, `YYYY-MM-DD` is used

**Comment by kossnocorp** [comment] 2018-05-25 07:29
I'm closing the issue as it's a duplicate. If you have any feedback, please continue in https://github.com/date-fns/date-fns/issues/347

**Closed by kossnocorp** 2018-05-25 07:29 UTC
Labels: ↩️ Duplicate

**Comment by patelkrunal78** [comment] 2019-10-02 15:10
You may Try format('2018-13-01', 'YYYY-DD-MM')
