### ISSUE TITLE
3.3.0 release broke several tests

### ISSUE THREAD

**Issue by fturmel** [date-fns/date-fns#3678] opened 2024-01-20 15:49 UTC
[ #c0aa54c](https://github.com/date-fns/date-fns/commit/c0aa54cc317b4f0525ac84aa4f7be63bd3bcbdba) most likely caused these issues.

**Issue 1**

~~Playwright test stuck/timing out on the `getUnixTime` function. Observed on [GitHub actions](https://github.com/date-fns/date-fns/actions/runs/7592665617/job/20682281971). Merging #3677 should fix this one.~~ #3677 merged in main

**Issue 2**

Failing unit tests in many time zones, oddly not surfaced by the CI actions. To reproduce: `env TZ=America/New_York npm run test`

![CleanShot 2024-01-20 at 10 08 21@2x](https://github.com/date-fns/date-fns/assets/4009209/2dba0686-b3ec-44a7-86bb-bcfd7ca02196)

**Comment by kossnocorp** [comment] 2024-01-21 02:18
Thank you a lot! I didn't have a chance to figure this out. Do I have to issue 3.3.1?

**Comment by fturmel** [comment] 2024-01-21 04:20
> Thank you a lot! I didn't have a chance to figure this out. Do I have to issue 3.3.1?

Good question, for #3677 maybe not. Quick tests with Vite and Parcel using the NPM published v3.3.0 seemed to work and the path got resolved. Is it possible that it could cause problems if people are shipping un-bundled ESM directly to browsers?

With that said, maybe I wasn't clear but the failing node unit tests are a separate thing that has yet to be investigated and fixed. These are the concerning ones that would most likely require a new release.`Math.trunc()` seem to have introduced a bunch of time zone specific off-by-one errors. The majority seem ISO week related.

It also exposed a blind spot in the CI time zone testing strategy, as the tests pass with `TZ=utc` and `TZ=Asia/Singapore`, but fail with `TZ=America/New_York` and `TZ=Europe/Paris` (amongst others). I'm now also realizing that while there are 6 failing tests in the New York time zone, there are actually _14_ for Paris.

I'm going to re-open this issue if you don't mind.

**Comment by doberkofler** [comment] 2024-01-21 06:48
I don't know if this helps but for example `getISOWeek(new Date('06/07/2015'))` is also wrongly calculated as 22 instead of 23.

**Comment by kossnocorp** [comment] 2024-01-22 05:07
@fturmel thank you for repopening the issue, I'm on it!

**Comment by kossnocorp** [comment] 2024-01-22 06:34
So here's what happened:

Before the final v3 release, I made TZ tests optional as they take a long time to complete, and they rarely caught anything significant.

While I was working on this huge commit fixing bugs caused by incorrect rounding, I accidentally broke a few functions that actually relied on `Math.round`: https://github.com/date-fns/date-fns/commit/c0aa54cc317b4f0525ac84aa4f7be63bd3bcbdba

It completely slipped my mind that there might be tz bugs, and I didn't think of running the tz workflows.

So to fix the problem, I enabled TZ runs on the `main` branch and also fixed the affected functions: https://github.com/date-fns/date-fns/commit/7141e991165b265badace16627676e1a89dec2db

Additionally, a test that I added caught a DST bug in `getOverlappingDaysInIntervals` I didn't know of before, so I fixed it too: https://github.com/date-fns/date-fns/commit/cf8a564dc9d66a479b3bb4ded2a29556546d5aeb

To prevent such bugs from happening, I'll look into speeding up the tests and, of course, making sure they are green before a release.

The work is still in progress and will ship v3.3.1 later today.

**Comment by kossnocorp** [comment] 2024-01-22 09:35
It was fixed in `date-fns@3.3.1`.

Now, the tests on the main run for an hour, and I'm still determining if I can quickly fix that. I will investigate solutions before switching them back to manual mode. I hope to find out how to speed them up. What we have right now is unsustainable.

**Closed by kossnocorp** 2024-01-22 09:35 UTC
Labels: 🔥 Important
