### ISSUE TITLE
Is there a function equivalent to moment().tz(timezone)

### ISSUE THREAD

**Issue by hackerkid** [date-fns/date-fns#479] opened 2017-04-21 06:49 UTC
Is it possible to get the current time of a particular timezone? Something similar to this.
```js
var timezone = "America/Chicago";
moment().tz(timezone);
// Retrieves the local time of America/Chicago
```

**Comment by TroodoNmike** [comment] 2017-05-17 08:13
Also interested in this. Anyone can think of how to force timezone to be used?

**Comment by n3o77** [comment] 2017-06-20 19:25
I'm looking forward for this as well. It's already discussed in #180 and here's the repo: https://github.com/date-fns/tzdata-fns

**Comment by benmccann** [comment] 2017-11-22 21:33
The Moment team recently shipped a new library called [Luxon](http://moment.github.io/luxon/), which uses the Intl.DateTimeFormat APIs to provide time zone support by ripping the time zone data out of the strings generated by this API. Perhaps you could borrow [the code](https://github.com/moment/luxon/blob/master/src/zones/IANAZone.js) (it's MIT licensed) to remove the need for [tzdata-fns](https://github.com/date-fns/tzdata-fns) or to make it much smaller.

**Comment by benmccann** [comment] 2017-12-31 16:05
It looks like this issue should be closed as a duplicate of https://github.com/date-fns/date-fns/issues/180

**Comment by havenchyk** [comment] 2018-01-24 12:23
@kossnocorp @leshakoss please, close this issue in favor of #180

**Closed** 2018-01-24 15:19 UTC
