### ISSUE TITLE
[locale: sk] `formatRelative` error

### ISSUE THREAD

**Issue by neupauer** [date-fns/date-fns#2560] opened 2021-07-23 12:20 UTC
**Version of date-fns**
2.22.1

**Locale**
sk (Slovak)
https://github.com/date-fns/date-fns/tree/master/src/locale/sk

**Reproduction repository**
https://stackblitz.com/edit/js-phoirz?devtoolsheight=33&file=index.js

`formatRelative` function with the specific input throws an error **Error: Format string contains an unescaped latin alphabet character `v`**

```js
formatRelative(new Date("2021-07-29T11:30:23.000Z"), new Date("2021-07-23T12:09:22.607Z"), { locale: sk })
```

**Comment by fturmel** [comment] 2021-07-23 12:30
Dupe of #2083, fix in PR #2540

**Closed** 2021-07-23 12:54 UTC
