### ISSUE TITLE
Unterminated comment

### ISSUE THREAD

**Issue by judemanutd** [date-fns/date-fns#2311] opened 2021-03-11 17:40 UTC
Library Version : 2.19.0

Upgraded from 2.18.0 to 2.19.0 and received the following error, downgrading back to 2.18.0 fixes it

```
./node_modules/date-fns/esm/isMatch/index.js
SyntaxError: /home/VSCodeProjects/project/node_modules/date-fns/esm/isMatch/index.js: Unterminated comment (4:0)

  2 | import isValid from "../isValid/index.js";
  3 | import requiredArgs from "../_lib/requiredArgs/index.js";
> 4 | /**
    | ^
  5 |  * @name isMatch
  6 |  * @category Common Helpers
  7 |  * @summary validates the date string against given formats
```

**Comment by fturmel** [comment] 2021-05-02 17:30
There has been a few new releases since this issue was created. Are you still experiencing the syntax error with the latest version?

If so, could you provide a bit more details about your setup and when this occurs? I can't replicate the problem on my end. Not sure if I can help, but I'm certainly curious about it!

**Comment by arsdehnel** [comment] 2021-05-27 04:19
I'm getting this same `Unterminated comment` issue today using 2.21.3 although it's on `esm/setDate/index.js` for me:

```javascript
failed Building development bundle - 35.642s
ERROR in ./node_modules/date-fns/esm/setDate/index.js 4:0
Module parse failed: Unterminated comment (4:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See
https://webpack.js.org/concepts#loaders
| import toDate from "../toDate/index.js";
| import requiredArgs from "../_lib/requiredArgs/index.js";
> /**
|  * @name setDate
|  * @category Day Helpers
 @ ./node_modules/date-fns/esm/index.js 166:0-56 166:0-56
 @ ./src/templates/subpage.jsx 14:0-44 59:39-47 187:5-11
 @ ./src/routing/router.jsx 12:0-51 73:17-32 83:17-32 93:17-32 263:17-32
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 31:11-33:5
 @ ./.cache/app.js 17:0-52 30:0-86 32:27-40 30:0-86

webpack compiled with 1 error
```

Running `yarn add date-fns@2.20` resolves this for me.  The weird thing is that when I go to https://registry.yarnpkg.com/date-fns/-/date-fns-2.21.3.tgz#8f5f6889d7a96bbcc1f0ea50239b397a83357f9b (which is the URL in my `yarn.lock` file) and open the tarball there I see the whole file's contents at `esm/setDate/index.js`.  Seems like somewhere in the yarn installation process it's not unpacking it all the way or something.  

I did a `yarn cache clear` and trying to re-install and now I see this in the install logs:

```log
error An unexpected error occurred: "https://registry.yarnpkg.com/date-fns/-/date-fns-2.21.3.tgz: ESOCKETTIMEDOUT"
```

Honestly based on this and the fact that my browser get the tarball and extracts it fine I don't know that it's something on your side to fix... seems like something with how yarn on my machine is interacting with the yarn registry.

**Comment by fturmel** [comment] 2021-05-27 19:53
@arsdehnel thanks for this!

First off, just to confirm... did you open the file `./node_modules/date-fns/esm/setDate/index.js` directly in your code editor to see if it was truncated? What about the `toDate` and `requiredArgs` files getting imported? Were some of the files missing or corrupted?

I can think of a few things to try out (if you're willing) that might give us a bit more info if you're still experiencing the issue after 12+ hours of posting. It could certainly be a network/yarn issue, but the timeout could've been a red herring or a separate issue altogether.

**1: Take your project's code and configurations out of the equation**

I put together a CRA template with the simplest usage of setDate possible with v2.21.3 over here: https://github.com/fturmel/simple-date-fns-demo
Are you able to clone the repo and get it to run with `yarn cache clean && yarn install && yarn start`? What if you pin the date-fns version to 2.20.0 in this project?

**2: Take yarn out of the equation**

In your project, can you manually replace the content of `node_modules/date-fns/` with the content of the tarball from the registry downloaded with your browser? Do it with both 2.20.0 and 2.21.3 and see if you observe the same behavior.
https://registry.yarnpkg.com/date-fns/-/date-fns-2.21.3.tgz
https://registry.yarnpkg.com/date-fns/-/date-fns-2.20.0.tgz

If v2.21.3 fails when you unpack it manually, could you share the tarball file used here so I can diff it and see if I can reproduce? (what if the file was corrupted or different only on some of the registry's CDN nodes?)

**3 : Misc network and yarn test ideas**

* update yarn to latest 1.x version. v1.16.0 introduced retry on network failure that could help https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md#1160
* yarn's install and add command have a network-timeout flag you could try
* there is also a --har flag for the install and add commands that will record network activity and dump to a HAR file
* verify that there isn't an http proxy that is coming into play in the configs https://classic.yarnpkg.com/en/docs/cli/config/
* try installing while on tethered LTE or while connected to a VPN so you're not using the same network route / CDN node

**Comment by fturmel** [comment] 2021-12-12 19:53
Going to close this, hope you both figured things out. If not, please comment and we can re-open the issue.

**Closed by fturmel** 2021-12-12 19:53 UTC
Labels: 🤹‍♂️ Support
