### ISSUE TITLE
Incorrect result across DST in differenceInDays

### ISSUE THREAD

**Issue by standy** [date-fns/date-fns#533] opened 2017-07-17 22:30 UTC
Calculating differenceInDays fails across DST

Example:
For London 2017-03-26, 01:00 clocks were turned forward 1 hour to 02:00
https://www.timeanddate.com/time/change/uk/london?year=2017
```
const d1 = new Date(2017, 2, 27, 1);
const d2 = new Date(2017, 2, 26, 2);
differenceInDays(d1, d2) === 1 // should be '0'
```

**Comment by kossnocorp** [comment] 2017-07-28 09:17
Thank you for reporting! We'll take a look as soon as possible.

**Comment by lewell94** [comment] 2019-05-23 15:46
Hi, is there any news on a fix for this? We have just encountered this issue using 1.30.1

**Comment by victormoukhortov** [comment] 2019-10-21 22:16
I am also having this issue - any updates?

**Comment by dcousens** [comment] 2019-11-06 03:40
I concur that `differenceInDays` ignores DST,  but `differenceInHours`, `differenceInSeconds` account for DST.

That is to say, `differenceInDays` does not operate on the local time date.

```
const A = new Date('2019-10-06 01:00:00') // day before DST
const B = new Date('2019-10-07 01:00:00') // 1 hour before DST
const C = new Date('2019-10-08 01:00:00') // day after DST
console.log({
  days: differenceInDays(B, A),
  hours: differenceInHours(B, A),
  seconds: differenceInSeconds(B, A),
})
// { days: 1, hours: 23, seconds: 82800 }

console.log({
  days: differenceInDays(C, B),
  hours: differenceInHours(C, B),
  seconds: differenceInSeconds(C, B),
})
// { days: 1, hours: 24, seconds: 86400 }
```

**Comment by canvaspixels** [comment] 2019-11-18 18:20
differenceInDays(new Date('2019-01-17T00:00:00.000Z'), new Date('2018-10-08T00:00:00.000Z')) for me returns 100 for me in my node environment (using date-fns 2.7.0) right now (current date 18/Nov) from London, UK.

When I set TZ=UTC environment variable before running the script it, it returns 101 which is what I expect.

**Comment by victormoukhortov** [comment] 2019-11-18 18:27
@canvaspixels how would you expect the difference in days to be different based on time zone? two timestamps should always have the same difference regardless of timezone.

**Comment by dcousens** [comment] 2019-11-18 20:29
@victormoukhortov each `difference*` function uses local time to calculate the difference - except `differenceInDays`.  This means rudimentary date math doesn't add up, and this difference is not documented.

**Comment by victormoukhortov** [comment] 2019-11-18 21:18
>  each difference* function uses local time to calculate the difference - except differenceInDays.

This seems like a fundamental breach in expectations. The difference between two points in time is fixed and does not change. The `difference*` functions should convert _from_ and _to_ times to UTC before calculating the difference.

**Comment by dcousens** [comment] 2019-11-18 22:34
Maybe.  But most times I want the local time difference.  Maybe `differenceInLocalTime*` could be provided.

**Comment by victormoukhortov** [comment] 2019-11-18 22:40
@dcousens I'm curious what your use case is for wanting the difference between two points in time to vary depending on your time zone. Say you have something - say a soccer match - that starts in two days. The obvious use case is to calculate the difference between the current time and the match start time. This difference is the same regardless of what time zone you happen to be in.

**Comment by dcousens** [comment] 2019-11-18 23:04
In a DST change-over,  a user typically expects to see the "number of days" between 8am today and 8am tomorrow, to be 1 day.

**Comment by canvaspixels** [comment] 2019-11-19 09:26
> @canvaspixels how would you expect the difference in days to be different based on time zone? two timestamps should always have the same difference regardless of timezone.

Exactly, that's what i'm saying. If i'm passing those 2 dates, that explicitly include the timezone the answer should always be the same, in this case 101. But what confuses me further is that i'm on GMT right now which is the same as UTC. So i've no idea why it returns 100.

**Comment by canvaspixels** [comment] 2019-11-19 09:28
Oh, is your question around if I didn't pass the timezone?

**Comment by dcousens** [comment] 2020-01-08 00:12
@marnusw are you open to a PR for this?

**Comment by marnusw** [comment] 2020-01-08 18:40
@dcousens Are you proposing to add a similar function to `date-fns-tz` that will take a DST crossing into account? If that is the case, sure.

**Comment by dcousens** [comment] 2020-01-08 22:59
Actually no,  I meant fixing the [behavioral inconsistency](https://github.com/date-fns/date-fns/issues/533#issuecomment-550128891) in this library!
@kossnocorp @leshakoss

**Comment by dcousens** [comment] 2020-02-05 02:22
@victormoukhortov please see https://github.com/date-fns/date-fns/pull/1630 - it highlights the fact that `differenceInDays` was not using UTC but local time;  we had it reversed.

**Closed** 2020-04-09 17:26 UTC
Labels: 🐛 Bug, 👩‍🔬 Needs triage

**Comment by justingrant** [comment] 2020-05-05 21:32
The fix for this issue in #1630 unfortunately caused a regression #1750 which broke my project last week.

I just submitted a PR #1754 which replaces #1630 (which fixed #533 in 2.12) with a different fix for #533 but which also avoids triggering #1750.

Note that my PR takes DST into account. This was needed because (copying from the PR): 

>  imagine a user measures a 7-day period from (local) noon to (local) noon one week later. If we only diff 24-hour periods, then that period would measure 7 days most of the year, but would return 6 days if DST started in the middle. This intermittent variation is a certain cause of hard-to-diagnose bugs, and is also different from how date-fns has behaved for a long time. That's why this PR goes back to the 2.11 behavior of taking DST into account. BTW, if a developer wants to ignore DST and just count 24-hour periods, this PR documents one way (`Math.floor(differenceInHours(dateLeft, dateRight)/24)|0`) in user-visible JSDoc comments.

**Comment by dcousens** [comment] 2020-05-06 23:12
And now my project is broken.
The issue is that `differenceInDays` is,  after #1754, inconsistent with `differenceInHours` again.
We have 1 set of functions operating on UTC,  and another operating on local time.

**Comment by dcousens** [comment] 2020-05-06 23:40
And now my project is broken.
The issue is that `differenceInDays` is,  after #1754, inconsistent with `differenceInHours` again.
We have 1 set of functions operating on UTC,  and another operating on local time.

These should probably each be indicated in the documentation.

I think the only option now is to document the API inconsistencies,  and if we want to resolve the situation,  start discussing a new major version.

>  This intermittent variation is .... different from how date-fns has behaved for a long time. That's why this PR goes back to the 2.11 behavior of taking DST into account.

From my own investigation,  it appears that
```js
differenceInYears: Local
differenceInQuarters: Local
differenceInMonths: Local
differenceInWeeks: Local
differenceInDays: Local@<2.12, UTC@2.12, Local@2.13
differenceInHours: UTC
differenceInMinutes: UTC
differenceInSeconds: UTC
differenceInMilliseconds: UTC
```

**Comment by justingrant** [comment] 2020-05-07 01:20
Hi @dcousens - Yep, your investigation is correct. Math with days (and larger) units use local time, while math with hours (and smaller) units uses UTC. AFAIK, this is consistent with behavior of `add*`/`sub*` functions, and also matches how moment.js has behaved [since 2011](https://github.com/moment/moment/issues/78#issuecomment-2979637). It's also consistent with JS's own `Date.setDate` API which tries to keep local time constant when adding or subtracting days.

It's not surprising that this behavior was chosen, given that hours are always the same length so UTC math is always safe.  Also, UTC math for hours (and smaller) units aligns with colloquial user expectations. If I say "I'll meet you at the bar in 2 hours" then I don't mean "I'll probably meet you in 120 minutes but maybe in 180 minutes and maybe in 60 minutes, depending on what Saturday night this is."

The reverse is true for days (and larger) units which have different lengths depending on time zone and time of year, so plain UTC math can be problematic for many use-cases. User expectations are also different. If my friend asks me to reschedule a 6:00PM diner reservation for the same time a week later, he won't expect to sometimes eat at 5:00PM or 7:00PM depending on the time of year.

There are also valid use-cases where ignoring DST is OK, like displaying relative time lengths (e.g. "2 days ago" above GitHub comments) or any case where there's no user expectation that local times stay the same across dates.  But the JS ecosystem seems to have decided long ago that local day math is the default behavior and UTC day math should be opt-in.

> I think the only option now is to document the API inconsistencies, and if we want to resolve the situation, start discussing a new major version.

Yep, agreed. Changing expected API behavior should only happen in a new major version.  That said, given that local day math seems to be the default across the JS ecosystem, I'd recommend that local remain the default and UTC should be opt-in, with a nice side effect of not needing a new major version. 

One choice would be to point users who want UTC behavior to the [UTC submodule](https://date-fns.org/v2.13.0/docs/Getting-Started#submodules). I don't know how mature that submodule is today.. and if not then I'm sure PRs would be welcome! ;-)

> These should probably each be indicated in the documentation.

Agreed. #1754 updated API docs and examples to clarify behavior. There's also explanation and a code sample for avoiding DST behavior if that's what's desired. Here's the newly-published docs for [`differenceInDays`](https://date-fns.org/v2.13.0/docs/differenceInDays): 

> Get the number of full day periods between two dates. Fractional days are truncated towards zero.
>
> One "full day" is the distance between a local time in one day to the same local time on the next or previous day. A full day can sometimes be less than or more than 24 hours if a daylight savings change happens between two dates.
>
> To ignore DST and only measure exact 24-hour periods, use this instead: `Math.floor(differenceInHours(dateLeft, dateRight)/24)|0`.
> 

And for [`differenceInWeeks`](https://date-fns.org/v2.13.0/docs/differenceInWeeks):

> Get the number of full weeks between two dates. Fractional weeks are truncated towards zero.
> 
> One "full week" is the distance between a local time in one day to the same local time 7 days earlier or later. A full week can sometimes be less than or more than 7*24 hours if a daylight savings change happens between two dates.
> 
> To ignore DST and only measure exact 7\*24-hour periods, use this instead: `Math.floor(differenceInHours(dateLeft, dateRight)/(7*24))|0`.
>
