### ISSUE TITLE
[TS] - type aliases are polluting the global scope

### ISSUE THREAD

**Issue by ValentinH** [date-fns/date-fns#1768] opened 2020-05-12 09:37 UTC
I've noticed that the type aliases like `Locale` are defined globally: https://github.com/date-fns/date-fns/blob/master/typings.d.ts#L35

Because of this, if I have a custom `Locale` type in my project, the one from `date-fns` is always suggested first. More importantly, I'm actually able to use `Locale` without importing it.

This is actually the case for all the types defined outside the `dates-fns` module:
https://github.com/date-fns/date-fns/blob/master/typings.d.ts#L5-L86

One solution would be to encapsulate them all in a namespace like:
```ts
declare namespace DateFns {
  type Locale = { }
}
```

and then to reference them within the `d.ts` file with `DateFns.Locale` instead of just `Locale`.

I'd be happy to submit a PR for this if you agree. However, I've seen that the `d.ts` was auto-generated so I'm not sure how to do it.

**Comment by dkozickis** [comment] 2020-05-13 13:52
That was discovered here - https://github.com/date-fns/date-fns/issues/1472 , and unfortunately would be a breaking change. To be fixed in v3, but no timelines yet.

Closing this as dupe of #1472, thank you!

**Closed by dkozickis** 2020-05-13 13:52 UTC

**Comment by ValentinH** [comment] 2020-05-13 18:08
Lol I am actually the writer of the issue you linked. I was sure I wrote one a while ago but didn't manage to find it back. 

Sorry ^^

**Comment by dkozickis** [comment] 2020-05-15 18:47
Right :D welcome back!
