### ISSUE TITLE
Formatted date inconsistency in daylight saving time changes

### ISSUE THREAD

**Issue by zzal** [date-fns/date-fns#1657] opened 2020-03-06 22:13 UTC
Hi, I'm getting these time-zoned dates, in fr-CA locale, with TZ set to "America/Toronto":

```
"2020-03-07T23:00:00.000Z": 7 mars 2020 18:00
"2020-03-08T00:00:00.000Z": 7 mars 2020 19:00
"2020-03-08T01:00:00.000Z": 7 mars 2020 20:00
"2020-03-08T02:00:00.000Z": 7 mars 2020 21:00
"2020-03-08T03:00:00.000Z": 7 mars 2020 21:00
"2020-03-08T04:00:00.000Z": 7 mars 2020 22:00
"2020-03-08T05:00:00.000Z": 7 mars 2020 23:00
"2020-03-08T06:00:00.000Z": 8 mars 2020 0:00
"2020-03-08T07:00:00.000Z": 8 mars 2020 3:00
"2020-03-08T08:00:00.000Z": 8 mars 2020 4:00
"2020-03-08T09:00:00.000Z": 8 mars 2020 5:00
"2020-03-08T10:00:00.000Z": 8 mars 2020 6:00
```

See the inconsistency? 
First the clock is supposed to be forwarded one hour at 02:00 local time.
I'm getting the same hour on Saturday 02:00:00 UTC than 03:00:00 UTC (?!).

I think we should get theses times:

```
"2020-03-07T23:00:00.000Z": 7 mars 2020 18:00
"2020-03-08T00:00:00.000Z": 7 mars 2020 19:00
"2020-03-08T01:00:00.000Z": 7 mars 2020 20:00
"2020-03-08T02:00:00.000Z": 7 mars 2020 21:00
"2020-03-08T03:00:00.000Z": 7 mars 2020 22:00
"2020-03-08T04:00:00.000Z": 7 mars 2020 23:00
"2020-03-08T05:00:00.000Z": 7 mars 2020 0:00
"2020-03-08T06:00:00.000Z": 8 mars 2020 1:00
"2020-03-08T07:00:00.000Z": 8 mars 2020 3:00
"2020-03-08T08:00:00.000Z": 8 mars 2020 4:00
"2020-03-08T09:00:00.000Z": 8 mars 2020 5:00
"2020-03-08T10:00:00.000Z": 8 mars 2020 6:00
```

**Comment by dkozickis** [comment] 2020-03-13 13:54
Seems to be a duplicate of https://github.com/date-fns/date-fns/issues/1618

**Closed by dkozickis** 2020-03-13 13:54 UTC
