### ISSUE TITLE
Can't resolve 'date-fns/_lib/format/longFormatters'

### ISSUE THREAD

**Issue by teknoalex** [date-fns/date-fns#1734] opened 2020-04-19 17:33 UTC
Code:
`import DateFnsUtils from '@date-io/date-fns';`

**Comment by GDIBass** [comment] 2020-04-21 21:46
You probably forgot to install date-fns
```
yarn add date-fns
```
or
```
npm i date-fns
```

**Comment by tashpjak** [comment] 2020-04-22 10:29
@GDIBass didnt help

**Comment by GDIBass** [comment] 2020-04-22 17:44
You'll need to provide more information then.  What does your package.json file look like.  How are you trying to use the package?  Webpack config?  Etc.

**Comment by NickRHR** [comment] 2020-04-25 20:56
same pb here

when using it with a material-ui/picker component << import DateFnsUtils from '@date-io/date-fns';

triggers:
Module not found: Can't resolve 'date-fns/_lib/format/longFormatters' in '/****/node_modules/@date-io/date-fns/build'

my jsconfig.json:
{
    "compilerOptions": {
      "baseUrl": "./src"
    },
    "include": ["src"],
    "exclude": ["node_modules", "build", "coverage", "dist", "lib"]
}

**Comment by dkozickis** [comment] 2020-05-01 08:56
Closing as this is

**Closed** 2020-05-01 08:57 UTC

**Comment by GermanBluefox** [comment] 2020-05-13 19:12
> import DateFnsUtils from '@date-io/date-fns';

Just add ```"date-fns": "2.13.0",``` to your package.json

**Comment by Dinnall** [comment] 2020-06-24 15:30
> > import DateFnsUtils from '@date-io/date-fns';
> 
> Just add `"date-fns": "2.13.0",` to your package.json

this didn't fix the error for me. still receiving `RangeError: Format string contains an unescaped latin alphabet character `n` error

**Comment by GDIBass** [comment] 2020-06-24 16:42
@Dinnall That looks like a different error.  It's probably worth opening another issue (make sure to include any required details and other relevant data like your package.json file, how you're using it and any other relevant items).

**Comment by Dinnall** [comment] 2020-06-24 17:26
> @Dinnall That looks like a different error. It's probably worth opening another issue (make sure to include any required details and other relevant data like your package.json file, how you're using it and any other relevant items).

 I just opened a new issue with.  **[here](https://github.com/date-fns/date-fns/issues/1857)**

**Comment by simonpolle** [comment] 2020-07-31 11:26
I got the same error after installing latest version:
RangeError: Format string contains an unescaped latin alphabet character `n`
(anonymous function)
C:/.../node_modules/date-fns/esm/format/index.js:421
  418 | }
  419 | 
  420 | if (firstCharacter.match(unescapedLatinCharacterRegExp)) {
> 421 |   throw new RangeError('Format string contains an unescaped latin alphabet character `' + firstCharacter + '`');
      | ^  422 | }
  423 | 
  424 | return substring;

**Comment by simonpolle** [comment] 2020-07-31 12:06
fixex the issue: npm i @date-io/date-fns@1.x date-fns

**Comment by ProteanCode** [comment] 2020-08-02 01:09
Having same issues

I am using this with material ui

    "@date-io/date-fns": "^2.8.0",
    "@material-ui/core": "^4.10.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/pickers": "^3.2.10",

**Comment by zahidalidev** [comment] 2020-10-01 22:10
npm i @date-io/date-fns@1.x date-fns after installing just restart the server only then, this worked

**Comment by Arnaldo-Manjate** [comment] 2020-11-07 23:23
thanks @zahidalidev

**Comment by dcsan** [comment] 2020-11-18 21:07
so the 2.x branch is broken? or somehow throws this error depending on other libraries?

"@date-io/date-fns": "^1.3.13",

**Comment by milos2211** [comment] 2021-01-11 20:49
I'm having the same issue with 2.16.1 version.

**Comment by Setoryz** [comment] 2021-01-18 17:50
Install the version below instead and run npm start after installation is completed

npm i --save date-fns@next @date-io/date-fns@1.x

**Comment by mahimsafa** [comment] 2021-11-02 13:40
I just removed package-lock.json file then it is working fine

**Comment by jkdas** [comment] 2021-11-06 05:01
> Install the version below instead and run npm start after installation is completed
> 
> npm i --save date-fns@next @date-io/date-fns@1.x

It works for me.... great.. thanks

**Comment by jkdas** [comment] 2021-11-06 05:08
> npm i @date-io/date-fns@1.x date-fns after installing just restart the server only then, this worked

It works fine for me.... it resolve the issue... thanks

**Comment by 3DGISKing** [comment] 2022-05-03 08:32
I got same error

**Comment by Abolfazl2647** [comment] 2024-01-10 16:23
it is all about the version.

```
"@date-io/date-fns-jalali": "^2.14.0",
    "@date-io/jalaali": "^2.16.0",
    "date-fns": "^2.28.0",
    "date-fns-jalali": "^2.28.0-1",
    ```
    
    i found out these versions can worke together.

**Comment by rwb196884** [comment] 2024-07-01 16:27
`"date-fns": "3.6.0"` is broken becuase of whatever this is. The last version I get get to work is `2.30.0`.

**Comment by meetzoo** [comment] 2024-08-02 14:23
For people coming here by searching this error,
if you are using https://www.npmjs.com/package/@mui/x-date-pickers and trying to update date-fns to 3.6.0 and encounter this error, check the docs
https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns
https://github.com/mui/mui-x/issues/13764#issuecomment-2215177870
you might need to update your date picker adapter to `import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';`

**Comment by ahmadi3d** [comment] 2024-08-17 18:20
> For people coming here by searching this error, if you are using https://www.npmjs.com/package/@mui/x-date-pickers and trying to update date-fns to 3.6.0 and encounter this error, check the docs https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns [mui/mui-x#13764 (comment)](https://github.com/mui/mui-x/issues/13764#issuecomment-2215177870) you might need to update your date picker adapter to `import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';`

This worked for me. I was moving my project from Create React App (JavaScript) to Vite (React TypeScript). Everything was working except for a single issue:
`import { AdapterDateFnsJalali } from '@mui/x-date-pickers/AdapterDateFnsJalali';`

This import was working in my current project, but I encountered an error in the new project stating it couldn’t find the module. I tried installing different versions and followed various suggestions from the internet, but none of them worked. I even initially tried your solution, but it didn’t work! Why? Because I needed to do both:

1- Import the module:
`import { AdapterDateFnsJalali } from '@mui/x-date-pickers/AdapterDateFnsJalali';`

2- Install the latest version of date-fns-jalali (I didn't need to do this in my previous project !).
Overall, this frustrating bug took almost 4 hours to resolve, especially because I thought it might be an issue with Vite or TypeScript. I had to test in different environments and try many solutions.

**Comment by oh-dony** [comment] 2025-02-11 15:19
> `import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';`
work!!! thanks

**Comment by maheshcodes12** [comment] 2025-03-14 06:25
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';

Worked for me! Thanks.

**Comment by Dharmanshu31** [comment] 2025-04-13 05:05
### 💡 Solution

This is actually a common issue that occurs when using multiple libraries that rely on different versions of `date-fns`.

You can check which versions are being used in your project by running the following command:


```bash  
npm ls date-fns
```

This will show you all the dependencies in your project that are using date-fns, along with their respective versions.

In my case, I had the following setup:

@mui/x-date-pickers@7.28.3 → depends on date-fns@2.30.0

react-date-range@2.0.1 → requires date-fns@3.0.0 or higher

My project had date-fns@4.0.1 installed

The issue happened because react-date-range was expecting a newer version, while @mui/x-date-pickers worked with 2.30.0, and my project had the latest version (4.0.1), which caused a version mismatch and missing exports.

✅ What worked for me:
Downgraded react-date-range from 2.0.1 to 1.4.0 (which uses date-fns@2.30.0)

Downgraded date-fns from 4.0.1 to 2.30.0 to match the version used by both libraries

Now all libraries use date-fns@2.30.0, and the issue is gone.

🔧 Summary of commands
To downgrade:

```bash
npm install date-fns@2.30.0
npm install react-date-range@1.4.0
