### ISSUE TITLE
bug in difference_in_days

### ISSUE THREAD

**Issue by yuanjiu041** [date-fns/date-fns#1104] opened 2019-02-26 08:57 UTC
![image](https://user-images.githubusercontent.com/29882936/53399784-8f8b2400-39e7-11e9-845b-78eb569f1e65.png)

**Comment by trevorah** [comment] 2019-04-01 16:00
@yuanjiu041 is this the same as https://github.com/date-fns/date-fns/issues/544 ?

**Comment by minitesh** [comment] 2019-04-26 05:58
@trevorah 
Its a duplicate of #544 and #606 

@yuanjiu041  Its already fixed but available only in alpha releases.

**Closed** 2019-06-03 13:58 UTC
Labels: 🤹‍♂️ Support
