### ISSUE TITLE
Different outcome on website console

### ISSUE THREAD

**Issue by ruisilva450** [date-fns/date-fns#1502] opened 2019-10-24 22:12 UTC
One of the main reasons for me to go to the documentation website is to be able to test the library on the dev console but often are times that there are differences between what's on documentation and what the dev console outputs.

For example, the parse function gives a completely different result from what is on the documentation:
```parse('50', 'yy', new Date(2018, 0, 1)) //=> Sat Jan 01 2050 00:00:00```

when tested on the console:
```dateFns.parse('50', 'yy', new Date(2018, 0, 1)) // => Wed Jan 01 5000 00:00:00 GMT+0100 (Central European Standard Time)```

Version highlighted on top right corner is 2.6.0
Browser: Chrome 77

**Comment by dkozickis** [comment] 2019-10-28 22:22
@kossnocorp date-fns documentation still has `date-fns@1.x` in console?

**Comment by kossnocorp** [comment] 2019-11-05 07:44
Duplicate of: https://github.com/date-fns/date-fns.org/issues/124

**Closed by kossnocorp** 2019-11-05 07:44 UTC
Labels: 📃 Docs, 🤹‍♂️ Support
