### ISSUE TITLE
Tree shaking issue 

### ISSUE THREAD

**Issue by wolfe111** [date-fns/date-fns#2589] opened 2021-08-12 08:39 UTC
I'm using date-fns in my project and I've just checked my bundle size using source-map-explorer and the size is over 80 kB. As you can see from the image attached, all the functions are there when I'm actually using only about 8. I'm importing the functions with es6 like ```import { addDays, parse } from 'date-fns';```

I'm currently using version 2.23.0

![image](https://user-images.githubusercontent.com/15180314/129165942-32d9e0f3-cd49-434d-a6ea-a1988c27de6a.png)

**Comment by fturmel** [comment] 2021-08-12 12:31
I can't reproduce the problem, and I'm not aware of tree shaking issues since #2339 got merged.

Maybe it's a bundler misconfiguration? Can you share additional details? Even better would be a minimal project that can demonstrate the issue.

**Comment by fturmel** [comment] 2021-12-03 17:12
I'm going to go ahead and close this since it doesn't appear to affect anyone else and you haven't provided additional information as requested.

If this is still a problem and you can share more details and reproducible steps, I will gladly have a look! Thanks

**Closed by fturmel** 2021-12-03 17:12 UTC
