### ISSUE TITLE
Error: "d[("get" + method)] is not a function" when select week or day view

### ISSUE THREAD

**Issue by RatchetNine76** [date-fns/date-fns#2836] opened 2021-12-09 13:35 UTC
Hello I am new to this, I try creating react calendar with react-big-calendar, date-fns, and DateTimePicker. I use DateTimePicker to type in the title, start and end date and time and saved it to localstorage.
![calendarProject](https://user-images.githubusercontent.com/33405640/145405658-61811a6a-883c-43a0-a9e1-6eda9ed483bf.png)
 when I try to view it in Week and Day, it would go Blank with the error d[("get" + method)] is not a function. I found out that I did not use true `Date` instances for event start and end dates, and try to solve it but would work fine when freshly added but will have the same problem when the page refreshed or add a new event. I dont what to do anymore, and I cant seem to find it online

```
import { useEffect, useState } from "react"
import format from "date-fns/format"
import parse from 'date-fns/parse'
import startOfWeek from 'date-fns/startOfWeek'
import getDay from 'date-fns/getDay'
import { dateFnsLocalizer } from "react-big-calendar"
import DateTimePicker from "react-datetime-picker/dist/DateTimePicker"
import 'react-datetime-picker/dist/DateTimePicker.css'
import 'react-calendar/dist/Calendar.css'
import 'react-clock/dist/Clock.css'
import { Calendar } from "react-big-calendar"
import 'react-big-calendar/lib/css/react-big-calendar.css'
import events from "../data/events"

const locales ={
"en-US" : require("date-fns/locale/en-US")
}

const localizer = dateFnsLocalizer({
format,
parse,
startOfWeek,
getDay,
locales
})

function Body() {
const [ newEvent, setNewEvent ] = useState({ title: "", start: "", end: ""})
/const [ allEvents, setAllEvents ] = useState(events)/
/const [currentEvent, setCurrentEvent] = useState("")/

const [ allEvents, setAllEvents ] = useState(() => {

    const savedEvents = localStorage.getItem("events")

    if (savedEvents) {
        return JSON.parse(savedEvents)
    } else {
        return events
    }
})

useEffect(() => {
    localStorage.setItem("events", JSON.stringify(allEvents))
}, [allEvents])

function handleAddEvent(e){
    e.preventDefault()
    
    if (newEvent !== "") {
        newEvent.start=parseJSON(newEvent.start);
        newEvent.end=parseJSON(newEvent.end);
        setAllEvents([
            ...allEvents,
            newEvent
        ])
    }
    
    console.log(newEvent)
    setNewEvent({ title: "", start: "", end: "" })
}  

return (
    <div className="cal-body">
        <div className="picker">
            <input 
                type="text"
                value={newEvent.title} 
                onChange={(e) => setNewEvent({...newEvent, title: e.target.value})}
            />
            <DateTimePicker
                disableClock={true}
                disableCalendar={true}
                selected={newEvent.start}
                dayPlaceholder="dd"
                monthPlaceholder="mm"
                yearPlaceholder="yyyy"
                hourPlaceholder="hh"
                minutePlaceholder="mm"
                onChange={(start) => setNewEvent({...newEvent, start})}
            />
            <DateTimePicker
                disableClock={true}
                disableCalendar={true}
                style={{
                    background: "white"
                }}
                selected={newEvent.end}
                dayPlaceholder="dd"
                monthPlaceholder="mm"
                yearPlaceholder="yyyy"
                hourPlaceholder="hh"
                minutePlaceholder="mm"
                onChange={(end) => setNewEvent({...newEvent, end})}
            />
            <button className="button" onClick={handleAddEvent}>Add</button>
        </div>
        
        <div className="calendar">
            <Calendar
                selectable
                localizer={localizer}
                events={allEvents}
                startAccessor="start"
                endAccessor="end"
                popup="true"
                onSelectEvent={() => setOpenModal(true)}
                style={{ 
                    height: 500, 
                    margin:"50px", 
                    background: "white", 
                    color: "black",
                    border: "2px solid black" }}
            />
        </div>
    </div>
)
}

export default Body
```

**Comment by fturmel** [comment] 2021-12-09 14:51
I'm going to close this since it's not a bug and has nothing to do with `date-fns`. You should try to get help from the react-big-calendar community on this.

Some direction to get you going:

I would suggest you consider using TypeScript to help you navigate the issues in this code snippet because they are mainly type-related.

Look at the `Event` type in the react-big-calendar docs, `start` and `end` properties are supposed to be Date objects and not strings as you mentioned yourself. https://jquense.github.io/react-big-calendar/examples/index.html#prop-events

```ts
Event {
  title: string,
  start: Date,
  end: Date,
  allDay?: boolean
  resource?: any,
}
```

Yet in your code, you keep assigning string values.

>  setNewEvent({ title: "", start: "", end: "" })

> const [ newEvent, setNewEvent ] = useState({ title: "", start: "", end: ""})

The `parseJSON` function is not imported in your file, and that function accepts a string as input.
> newEvent.start=parseJSON(newEvent.start);

More Date vs string type confusion:
> onChange={(start) => setNewEvent({...newEvent, start})}
> onChange={(end) => setNewEvent({...newEvent, end})}

Broken code:
> /const [ allEvents, setAllEvents ] = useState(events)/
> /const [currentEvent, setCurrentEvent] = useState("")/

newEvent is never a string, so this doesn't make much sense
> if (newEvent !== '') {

Good luck!

**Closed by fturmel** 2021-12-09 14:51 UTC
