### ISSUE TITLE
fromUnixTime() returning high year number when passed epoch timestamp with milliseconds

### ISSUE THREAD

**Issue by Zainzzkk** [date-fns/date-fns#2848] opened 2021-12-14 11:07 UTC
I have a date in format of epoch with milliseconds - 1639152079940 

When using an online converter, it correctly converts the timestamp to the date which is Friday, 10 December 2021 16:01:19.940

However, when using fromUnixTime() it returns +053912-08-30T14:12:20.000Z which is wrong.

Is it possible to support millisecond timestamps please?

**Comment by fturmel** [comment] 2021-12-14 13:44
Dupe of #2206

The Date constructor already natively supports timestamps in milliseconds. `fromUnixTime` takes in seconds, not milliseconds.

```js
import { fromUnixTime } from "date-fns";

const ms = 1639152079940;

console.log(new Date(ms).toISOString()); // 2021-12-10T16:01:19.940Z
console.log(fromUnixTime(ms / 1000).toISOString()); // 2021-12-10T16:01:19.000Z
```

**Closed by fturmel** 2021-12-14 13:44 UTC
