### ISSUE TITLE
intervalToDuration return invalid duration

### ISSUE THREAD

**Issue by mephistorine** [date-fns/date-fns#2261] opened 2021-02-28 08:10 UTC
```js
const start = new Date('2021-02-28T07:23:07.000Z')
const end = new Date('2021-02-28T07:38:18.096Z')
const result = intervalToDuration({ start, end })
/*
result = {
  "years": 0,
  "months": 1,
  "days": 27,
  "hours": 1319,
  "minutes": 158324,
  "seconds": 18998928
}
*/
```
if i swap the `start` and `end` everything works

```js
const start =  new Date('2021-02-28T07:38:18.096Z')
const end = new Date('2021-02-28T07:23:07.000Z')
const result = intervalToDuration({ start, end })
/*
result = {
  "years": 0,
  "months": 0,
  "days": 0,
  "hours": 0,
  "minutes": 15,
  "seconds": 11
}
*/
```

Note: The formatDistance function works correctly in any case

```js
const start = new Date('2021-02-28T07:23:07.000Z')
const end = new Date('2021-02-28T07:38:18.096Z')
const result2 = formatDistance(start, end, { addSuffix: true }) // in 15 minutes
```

**Comment by sbelczyk-sp** [comment] 2021-02-28 16:22
I have exactly the same issue. The fun part is that this bug occurs only on 28th Feb, change the month to January or march and it works fine.

**Comment by mephistorine** [comment] 2021-02-28 17:17
it issue is duplicate #2255

**Comment by tan75** [comment] 2021-02-28 19:15
Hi @mephistorine, @sbelczyk-sp 
Thank you for raising this issue.
A PR has already been opened to fix the above and hopefully it will be approved and released shortly.
@mephistorine I have added the dates you mentioned to one of the test cases and it worked out as expected.
I am going to close this issue as this is a dupe of #2255

**Closed by tan75** 2021-02-28 19:15 UTC

**Comment by mephistorine** [comment] 2021-02-28 19:19
@tan75 thanks!
